name: SW API Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

env:
  JWT_SECRET: secret

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ./coverage/lcov.info
