name: SW API Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

env:
  JWT_SECRET: secret

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test:coverage
